services:
  - type: web
    name: deploy-testing
    plan: free  # ใช้แผนฟรีแทน starter plan
    buildCommand: 'docker build -t deploy-testing .'
    startCommand: 'docker run -p 80:80 deploy-testing'
    envVars:
      - key: DB_CONNECTION
        value: mysql
      - key: DB_HOST
        value: deploy-testing.db.render.com
      - key: DB_DATABASE
        value: deploy-testing
      - key: DB_USERNAME
        value: nrk
      - key: DB_PASSWORD
        value: narakorn888999
