services:
  - type: web
    name: deploy-testing
    env: php
    plan: free  # ใช้แผนฟรีแทน starter plan
    buildCommand: 'composer install --optimize-autoloader --no-dev'
    startCommand: 'php artisan serve --host=0.0.0.0 --port=80'
    envVars:
      - key: DB_CONNECTION
        value: mysql
      - key: DB_HOST
        value: deploy-testing.db.render.com
      - key: DB_DATABASE
        value: deploy-testing
      - key: DB_USERNAME
        value: nrk
      - key: DB_PASSWORD
        value:
